{"name": "test_login_1_error[data0]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "21e16b98-d71e-4d5e-9f23-fccc94a172c0-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "cfbbfed8-15cf-43a1-9649-6f6e04f1278c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '', 'pwd': '', 'expected': '请输入手机号'}"}], "start": 1571365007890, "stop": 1571365013957, "uuid": "f014ee63-58a3-41f1-8b3d-9769bb29a09c", "historyId": "51efa93677dd5dab25fbeacbda681122", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "12940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}