{"name": "test_login_1_error[data1]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "1f0151b4-72ab-4766-a8a7-30e6724d7999-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '123', 'pwd': '', 'expected': '请输入正确的手机号'}"}], "start": 1571365020100, "stop": 1571365029131, "uuid": "5d328e98-6b79-4c19-9df6-9538ec63b86c", "historyId": "af66e56d33602761ce348aec2c1eee59", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "12940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}