{"name": "test_login_1_error[data0]", "status": "passed", "description": "异常登录", "attachments": [{"name": "log", "source": "6b8d9419-0711-4438-a9c7-88b555e70993-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1a0b9683-adf9-45ed-8e6e-77dfe45d2fe6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'username': '', 'pwd': '', 'expected': '请输入手机号'}"}], "start": 1571302823884, "stop": 1571302832782, "uuid": "9e1cdcec-e84f-45ce-b8fe-fbb6ced50c9e", "historyId": "51efa93677dd5dab25fbeacbda681122", "testCaseId": "09a1dfa16a6f8824208fd27bb36bdeba", "fullName": "test_login.TestLogin#test_login_1_error", "labels": [{"name": "tag", "value": "demo"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31LFQ9S"}, {"name": "thread", "value": "17160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}